DEBUG 2016-03-31 07:02:47,830 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:03:05,317 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:03:05,344 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:03:05,345 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 07:03:05,347 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 07:03:05,376 utils (0.001) 
            SELECT kc.`constraint_name`, kc.`column_name`,
                kc.`referenced_table_name`, kc.`referenced_column_name`
            FROM information_schema.key_column_usage AS kc
            WHERE
                kc.table_schema = 'benz' AND
                kc.table_name = 'portal_user'
        ; args=['benz', u'portal_user']
DEBUG 2016-03-31 07:03:05,377 utils (0.001) 
            SELECT c.constraint_name, c.constraint_type
            FROM information_schema.table_constraints AS c
            WHERE
                c.table_schema = 'benz' AND
                c.table_name = 'portal_user'
        ; args=['benz', u'portal_user']
DEBUG 2016-03-31 07:03:05,378 utils (0.000) SHOW INDEX FROM `portal_user`; args=None
DEBUG 2016-03-31 07:03:05,378 schema ALTER TABLE `portal_user` DROP FOREIGN KEY `portal_user_service_id_2ecc47d5_fk_portal_service_id`; (params [])
DEBUG 2016-03-31 07:03:05,786 utils (0.408) ALTER TABLE `portal_user` DROP FOREIGN KEY `portal_user_service_id_2ecc47d5_fk_portal_service_id`; args=[]
DEBUG 2016-03-31 07:03:05,787 schema ALTER TABLE `portal_user` DROP COLUMN `service_id` CASCADE; (params [])
DEBUG 2016-03-31 07:03:05,889 utils (0.102) ALTER TABLE `portal_user` DROP COLUMN `service_id` CASCADE; args=[]
DEBUG 2016-03-31 07:03:05,897 schema ALTER TABLE `portal_user` ADD COLUMN `service_name` varchar(256) NULL; (params [])
DEBUG 2016-03-31 07:03:05,957 utils (0.060) ALTER TABLE `portal_user` ADD COLUMN `service_name` varchar(256) NULL; args=[]
DEBUG 2016-03-31 07:03:05,958 schema ALTER TABLE `portal_user` ALTER COLUMN `service_name` DROP DEFAULT; (params [])
DEBUG 2016-03-31 07:03:05,966 utils (0.008) ALTER TABLE `portal_user` ALTER COLUMN `service_name` DROP DEFAULT; args=[]
DEBUG 2016-03-31 07:03:05,967 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 07:03:05,968 utils (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('portal', '0002_auto_20160331_0702', '2016-03-31 07:03:05.967964'); args=['portal', u'0002_auto_20160331_0702', u'2016-03-31 07:03:05.967964']
DEBUG 2016-03-31 07:03:05,985 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 07:03:05,986 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 07:03:05,988 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'logentry' AND `django_content_type`.`app_label` = 'admin'); args=('logentry', 'admin')
DEBUG 2016-03-31 07:03:05,992 utils (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (1) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(1,)
DEBUG 2016-03-31 07:03:05,993 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'admin'; args=('admin',)
DEBUG 2016-03-31 07:03:05,995 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'permission' AND `django_content_type`.`app_label` = 'auth'); args=('permission', 'auth')
DEBUG 2016-03-31 07:03:05,996 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'group' AND `django_content_type`.`app_label` = 'auth'); args=('group', 'auth')
DEBUG 2016-03-31 07:03:05,998 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'user' AND `django_content_type`.`app_label` = 'auth'); args=('user', 'auth')
DEBUG 2016-03-31 07:03:06,001 utils (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (2, 3, 4) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(2, 3, 4)
DEBUG 2016-03-31 07:03:06,002 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'auth'; args=('auth',)
DEBUG 2016-03-31 07:03:06,003 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'contenttype' AND `django_content_type`.`app_label` = 'contenttypes'); args=('contenttype', 'contenttypes')
DEBUG 2016-03-31 07:03:06,006 utils (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (5) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(5,)
DEBUG 2016-03-31 07:03:06,007 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'contenttypes'; args=('contenttypes',)
DEBUG 2016-03-31 07:03:06,008 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'session' AND `django_content_type`.`app_label` = 'sessions'); args=('session', 'sessions')
DEBUG 2016-03-31 07:03:06,011 utils (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (6) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(6,)
DEBUG 2016-03-31 07:03:06,012 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'sessions'; args=('sessions',)
DEBUG 2016-03-31 07:03:06,014 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'service' AND `django_content_type`.`app_label` = 'portal'); args=('service', 'portal')
DEBUG 2016-03-31 07:03:06,015 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'user' AND `django_content_type`.`app_label` = 'portal'); args=('user', 'portal')
DEBUG 2016-03-31 07:03:06,017 utils (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (8, 7) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(8, 7)
DEBUG 2016-03-31 07:03:06,019 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'portal'; args=('portal',)
DEBUG 2016-03-31 07:14:07,607 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:14:07,657 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:14:07,659 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 07:14:07,663 utils (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 07:26:21,817 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:26:21,866 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:26:21,867 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 07:26:21,870 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 07:27:39,580 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:27:39,634 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:27:39,636 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 07:27:39,640 utils (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
WARNING 2016-03-31 07:27:42,658 base Not Found: /portal/submit
DEBUG 2016-03-31 07:27:42,662 base Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
ERROR 2016-03-31 07:27:42,664 base Internal Server Error: /portal/submit
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 114, in process_response
    if self.should_redirect_with_slash(request):
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 79, in should_redirect_with_slash
    and urlresolvers.is_valid_path('%s/' % request.path_info, urlconf)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 668, in is_valid_path
    resolve(path, urlconf)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 534, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 376, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 248, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 255, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/benz/venv/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 136, in get_callable
    (lookup_view, mod_name))
ViewDoesNotExist: Could not import 'portal.view.submit'. View does not exist in module portal.view.
DEBUG 2016-03-31 07:28:38,137 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:28:38,185 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:28:38,186 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 07:28:38,189 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
WARNING 2016-03-31 07:28:40,712 base Not Found: /portal/submit
DEBUG 2016-03-31 07:28:40,716 base Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
ERROR 2016-03-31 07:28:40,722 base Internal Server Error: /portal/submit
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 114, in process_response
    if self.should_redirect_with_slash(request):
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 79, in should_redirect_with_slash
    and urlresolvers.is_valid_path('%s/' % request.path_info, urlconf)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 668, in is_valid_path
    resolve(path, urlconf)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 534, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 376, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 248, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 255, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/benz/venv/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 115, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/benz/portal/views.py", line 11, in <module>
    from plugin import *
  File "/home/benz/portal/plugin.py", line 6, in <module>
    import requests
ImportError: No module named requests
DEBUG 2016-03-31 07:29:08,527 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:29:08,577 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:29:08,578 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 07:29:08,581 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
WARNING 2016-03-31 07:29:10,044 base Not Found: /portal/submit
DEBUG 2016-03-31 07:29:10,049 base Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
ERROR 2016-03-31 07:29:10,094 base Internal Server Error: /portal/submit
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 115, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 99, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/portal/submit/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
WARNING 2016-03-31 07:32:16,843 base Not Found: /portal/submit
DEBUG 2016-03-31 07:32:16,847 base Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
ERROR 2016-03-31 07:32:16,848 base Internal Server Error: /portal/submit
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 115, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 99, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/portal/submit/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
DEBUG 2016-03-31 07:32:51,047 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:32:51,096 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:32:51,098 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 07:32:51,101 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
WARNING 2016-03-31 07:33:16,222 csrf Forbidden (CSRF cookie not set.): /portal/submit/
DEBUG 2016-03-31 07:33:54,690 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:33:54,736 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:33:54,738 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 07:33:54,740 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 07:33:57,868 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:33:57,870 utils (0.000) INSERT INTO `portal_user` (`name`, `mobile`, `email`, `sex`, `province`, `city`, `service_name`) VALUES ('sf', '1232221112', 'fdsf', '1', '2', NULL, '南宁恒信之星'); args=[u'sf', u'1232221112', u'fdsf', u'1', u'2', None, u'\u5357\u5b81\u6052\u4fe1\u4e4b\u661f']
ERROR 2016-03-31 07:33:57,870 base Internal Server Error: /portal/submit/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 59, in submit
    u.save()
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 700, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 728, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 812, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/models/base.py", line 851, in _do_insert
    using=using, raw=raw)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/benz/venv/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 112, in execute
    return self.cursor.execute(query, args)
  File "/home/benz/venv/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/benz/venv/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1366, "Incorrect string value: '\\xE5\\x8D\\x97\\xE5\\xAE\\x81...' for column 'service_name' at row 1")
DEBUG 2016-03-31 07:33:57,918 utils (0.000) SELECT `portal_user`.`id`, `portal_user`.`name`, `portal_user`.`mobile`, `portal_user`.`email`, `portal_user`.`sex`, `portal_user`.`province`, `portal_user`.`city`, `portal_user`.`service_name` FROM `portal_user` LIMIT 21; args=()
DEBUG 2016-03-31 07:34:45,515 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 07:34:45,516 utils (0.000) INSERT INTO `portal_user` (`name`, `mobile`, `email`, `sex`, `province`, `city`, `service_name`) VALUES ('sf', '1232221112', 'fdsf', '1', '2', NULL, '南宁恒信之星'); args=[u'sf', u'1232221112', u'fdsf', u'1', u'2', None, u'\u5357\u5b81\u6052\u4fe1\u4e4b\u661f']
DEBUG 2016-03-31 11:12:44,865 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:12:51,973 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:12:52,000 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:12:52,001 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:12:52,003 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 11:12:52,027 schema CREATE TABLE `portal_backuser` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `service_name` varchar(256) NULL, `password` varchar(64) NULL); (params None)
DEBUG 2016-03-31 11:12:52,118 utils (0.090) CREATE TABLE `portal_backuser` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `service_name` varchar(256) NULL, `password` varchar(64) NULL); args=None
DEBUG 2016-03-31 11:12:52,119 utils (0.001) SELECT engine FROM information_schema.tables WHERE table_name = 'portal_backuser'; args=[u'portal_backuser']
DEBUG 2016-03-31 11:12:52,120 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:12:52,121 utils (0.000) INSERT INTO `django_migrations` (`app`, `name`, `applied`) VALUES ('portal', '0003_backuser', '2016-03-31 11:12:52.120500'); args=['portal', u'0003_backuser', u'2016-03-31 11:12:52.120500']
DEBUG 2016-03-31 11:12:52,132 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:12:52,133 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 11:12:52,135 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'logentry' AND `django_content_type`.`app_label` = 'admin'); args=('logentry', 'admin')
DEBUG 2016-03-31 11:12:52,139 utils (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (1) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(1,)
DEBUG 2016-03-31 11:12:52,141 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'admin'; args=('admin',)
DEBUG 2016-03-31 11:12:52,142 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'permission' AND `django_content_type`.`app_label` = 'auth'); args=('permission', 'auth')
DEBUG 2016-03-31 11:12:52,144 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'group' AND `django_content_type`.`app_label` = 'auth'); args=('group', 'auth')
DEBUG 2016-03-31 11:12:52,145 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'user' AND `django_content_type`.`app_label` = 'auth'); args=('user', 'auth')
DEBUG 2016-03-31 11:12:52,148 utils (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (2, 3, 4) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(2, 3, 4)
DEBUG 2016-03-31 11:12:52,149 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'auth'; args=('auth',)
DEBUG 2016-03-31 11:12:52,150 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'contenttype' AND `django_content_type`.`app_label` = 'contenttypes'); args=('contenttype', 'contenttypes')
DEBUG 2016-03-31 11:12:52,153 utils (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (5) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(5,)
DEBUG 2016-03-31 11:12:52,154 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'contenttypes'; args=('contenttypes',)
DEBUG 2016-03-31 11:12:52,155 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'session' AND `django_content_type`.`app_label` = 'sessions'); args=('session', 'sessions')
DEBUG 2016-03-31 11:12:52,158 utils (0.000) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (6) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(6,)
DEBUG 2016-03-31 11:12:52,159 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'sessions'; args=('sessions',)
DEBUG 2016-03-31 11:12:52,160 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'service' AND `django_content_type`.`app_label` = 'portal'); args=('service', 'portal')
DEBUG 2016-03-31 11:12:52,162 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'user' AND `django_content_type`.`app_label` = 'portal'); args=('user', 'portal')
DEBUG 2016-03-31 11:12:52,163 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'backuser' AND `django_content_type`.`app_label` = 'portal'); args=('backuser', 'portal')
DEBUG 2016-03-31 11:12:52,164 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE (`django_content_type`.`model` = 'backuser' AND `django_content_type`.`app_label` = 'portal'); args=('backuser', 'portal')
DEBUG 2016-03-31 11:12:52,165 utils (0.000) INSERT INTO `django_content_type` (`app_label`, `model`) VALUES ('portal', 'backuser'); args=['portal', 'backuser']
DEBUG 2016-03-31 11:12:52,172 utils (0.001) SELECT `auth_permission`.`content_type_id`, `auth_permission`.`codename` FROM `auth_permission` INNER JOIN `django_content_type` ON (`auth_permission`.`content_type_id` = `django_content_type`.`id`) WHERE `auth_permission`.`content_type_id` IN (8, 9, 7) ORDER BY `django_content_type`.`app_label` ASC, `django_content_type`.`model` ASC, `auth_permission`.`codename` ASC; args=(8, 9, 7)
DEBUG 2016-03-31 11:12:52,174 utils (0.000) INSERT INTO `auth_permission` (`name`, `content_type_id`, `codename`) VALUES ('Can add back user', 9, 'add_backuser'), ('Can change back user', 9, 'change_backuser'), ('Can delete back user', 9, 'delete_backuser'); args=(u'Can add back user', 9, u'add_backuser', u'Can change back user', 9, u'change_backuser', u'Can delete back user', 9, u'delete_backuser')
DEBUG 2016-03-31 11:12:52,179 utils (0.000) SELECT `django_content_type`.`id`, `django_content_type`.`app_label`, `django_content_type`.`model` FROM `django_content_type` WHERE `django_content_type`.`app_label` = 'portal'; args=('portal',)
DEBUG 2016-03-31 11:14:45,189 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:14:45,241 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:14:45,242 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:14:45,245 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
WARNING 2016-03-31 11:15:00,951 base Not Found: /portal/in
DEBUG 2016-03-31 11:15:00,955 base Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
ERROR 2016-03-31 11:15:00,957 base Internal Server Error: /portal/in
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 114, in process_response
    if self.should_redirect_with_slash(request):
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 79, in should_redirect_with_slash
    and urlresolvers.is_valid_path('%s/' % request.path_info, urlconf)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 668, in is_valid_path
    resolve(path, urlconf)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 534, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 376, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 248, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 255, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/benz/venv/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 115, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/benz/portal/views.py", line 64
    def in(request):
         ^
SyntaxError: invalid syntax
ERROR 2016-03-31 11:15:04,964 base Internal Server Error: /portal/in/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 134, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 376, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 248, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 255, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/benz/venv/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 115, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/benz/portal/views.py", line 64
    def in(request):
         ^
SyntaxError: invalid syntax
DEBUG 2016-03-31 11:15:56,311 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:15:56,358 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:15:56,360 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:15:56,365 utils (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
WARNING 2016-03-31 11:15:58,090 base Not Found: /portal/in/
DEBUG 2016-03-31 11:15:58,095 base Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
ERROR 2016-03-31 11:16:02,341 base Internal Server Error: /portal/inexc/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 65, in inexc
    data = xlrd.open_workbook('excelFile.xls')
  File "/home/benz/venv/lib/python2.7/site-packages/xlrd/__init__.py", line 394, in open_workbook
    f = open(filename, "rb")
IOError: [Errno 2] No such file or directory: 'excelFile.xls'
DEBUG 2016-03-31 11:16:21,607 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:16:21,658 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:16:21,659 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:16:21,662 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
ERROR 2016-03-31 11:16:22,648 base Internal Server Error: /portal/inexc/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 68, in inexc
    for i in range(cols):
TypeError: range() integer end argument expected, got list.
DEBUG 2016-03-31 11:16:35,217 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:16:35,264 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:16:35,266 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:16:35,269 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
ERROR 2016-03-31 11:16:37,630 base Internal Server Error: /portal/inexc/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 68, in inexc
    for i in range(cols):
TypeError: range() integer end argument expected, got list.
DEBUG 2016-03-31 11:17:32,489 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:17:32,541 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:17:32,542 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:17:32,546 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
ERROR 2016-03-31 11:17:33,529 base Internal Server Error: /portal/inexc/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 68, in inexc
    for i in range(cols):
TypeError: range() integer end argument expected, got list.
DEBUG 2016-03-31 11:18:52,767 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:18:52,815 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:18:52,816 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:18:52,819 utils (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
ERROR 2016-03-31 11:18:55,393 base Internal Server Error: /portal/inexc/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 69, in inexc
    for i in range(cols):
TypeError: range() integer end argument expected, got list.
DEBUG 2016-03-31 11:19:20,217 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:19:20,262 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:19:20,263 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:19:20,267 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
ERROR 2016-03-31 11:19:21,285 base Internal Server Error: /portal/inexc/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 69, in inexc
    for i in range(cols):
TypeError: range() integer end argument expected, got list.
DEBUG 2016-03-31 11:19:41,103 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:19:41,152 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:19:41,153 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:19:41,156 utils (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 11:22:03,393 utils (0.001) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:22:03,441 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:22:03,442 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:22:03,446 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
ERROR 2016-03-31 11:22:08,883 base Internal Server Error: /portal/inexc/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 71, in inexc
    p = ramdom.randint(100000,999999);
NameError: global name 'ramdom' is not defined
DEBUG 2016-03-31 11:22:23,009 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:22:23,058 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:22:23,059 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 11:22:23,063 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 11:22:23,888 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 11:22:23,890 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('南方腾星', '518462'); args=[u'\u5357\u65b9\u817e\u661f', u'518462']
DEBUG 2016-03-31 11:22:23,900 utils (0.001) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('南方腾星梅林店', '444778'); args=[u'\u5357\u65b9\u817e\u661f\u6885\u6797\u5e97', u'444778']
DEBUG 2016-03-31 11:22:23,911 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('深圳鹏峰', '432309'); args=[u'\u6df1\u5733\u9e4f\u5cf0', u'432309']
DEBUG 2016-03-31 11:22:23,917 utils (0.001) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('深圳福日', '840727'); args=[u'\u6df1\u5733\u798f\u65e5', u'840727']
DEBUG 2016-03-31 11:22:23,923 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('深圳仁孚', '911345'); args=[u'\u6df1\u5733\u4ec1\u5b5a', u'911345']
DEBUG 2016-03-31 11:22:23,928 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('深圳中升星辉', '767763'); args=[u'\u6df1\u5733\u4e2d\u5347\u661f\u8f89', u'767763']
DEBUG 2016-03-31 11:22:23,935 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('仁孚鹏星行奔驰 ', '472275'); args=[u'\u4ec1\u5b5a\u9e4f\u661f\u884c\u5954\u9a70 ', u'472275']
DEBUG 2016-03-31 11:22:23,943 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('深圳大兴奔驰', '474147'); args=[u'\u6df1\u5733\u5927\u5174\u5954\u9a70', u'474147']
DEBUG 2016-03-31 11:22:23,957 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('深圳大兴罗湖奔驰', '228940'); args=[u'\u6df1\u5733\u5927\u5174\u7f57\u6e56\u5954\u9a70', u'228940']
DEBUG 2016-03-31 11:22:23,964 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('南宁恒信之星', '769413'); args=[u'\u5357\u5b81\u6052\u4fe1\u4e4b\u661f', u'769413']
DEBUG 2016-03-31 11:22:23,970 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('南宁冠星', '378980'); args=[u'\u5357\u5b81\u51a0\u661f', u'378980']
DEBUG 2016-03-31 11:22:23,976 utils (0.001) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('广西龙星行', '681114'); args=[u'\u5e7f\u897f\u9f99\u661f\u884c', u'681114']
DEBUG 2016-03-31 11:22:23,981 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('泉州闽星', '704702'); args=[u'\u6cc9\u5dde\u95fd\u661f', u'704702']
DEBUG 2016-03-31 11:22:23,987 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('泉州中升之星', '835668'); args=[u'\u6cc9\u5dde\u4e2d\u5347\u4e4b\u661f', u'835668']
DEBUG 2016-03-31 11:22:23,993 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('泉州之星', '922910'); args=[u'\u6cc9\u5dde\u4e4b\u661f', u'922910']
DEBUG 2016-03-31 11:22:23,998 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('泉州瑞星', '817405'); args=[u'\u6cc9\u5dde\u745e\u661f', u'817405']
DEBUG 2016-03-31 11:22:24,003 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('', '243306'); args=['', u'243306']
DEBUG 2016-03-31 11:22:24,009 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('石狮大长江红星', '907649'); args=[u'\u77f3\u72ee\u5927\u957f\u6c5f\u7ea2\u661f', u'907649']
DEBUG 2016-03-31 11:22:24,014 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('泉州中升星辉', '707107'); args=[u'\u6cc9\u5dde\u4e2d\u5347\u661f\u8f89', u'707107']
DEBUG 2016-03-31 11:22:24,021 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('厦门东之星', '107483'); args=[u'\u53a6\u95e8\u4e1c\u4e4b\u661f', u'107483']
DEBUG 2016-03-31 11:22:24,035 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('厦门东之星.星聚点', '182410'); args=[u'\u53a6\u95e8\u4e1c\u4e4b\u661f.\u661f\u805a\u70b9', u'182410']
DEBUG 2016-03-31 11:22:24,042 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('厦门航星', '735110'); args=[u'\u53a6\u95e8\u822a\u661f', u'735110']
DEBUG 2016-03-31 11:22:24,048 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('江西华宏星', '964570'); args=[u'\u6c5f\u897f\u534e\u5b8f\u661f', u'964570']
DEBUG 2016-03-31 11:22:24,055 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('江西华宏名驰', '215096'); args=[u'\u6c5f\u897f\u534e\u5b8f\u540d\u9a70', u'215096']
DEBUG 2016-03-31 11:22:24,061 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('南昌东之星', '382648'); args=[u'\u5357\u660c\u4e1c\u4e4b\u661f', u'382648']
DEBUG 2016-03-31 11:22:24,068 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('南昌迎星', '704590'); args=[u'\u5357\u660c\u8fce\u661f', u'704590']
DEBUG 2016-03-31 11:22:24,077 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('南昌中升之星', '738330'); args=[u'\u5357\u660c\u4e2d\u5347\u4e4b\u661f', u'738330']
DEBUG 2016-03-31 11:22:24,083 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('佛山中升之星', '199515'); args=[u'\u4f5b\u5c71\u4e2d\u5347\u4e4b\u661f', u'199515']
DEBUG 2016-03-31 11:22:24,091 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('佛山中升星辉', '646644'); args=[u'\u4f5b\u5c71\u4e2d\u5347\u661f\u8f89', u'646644']
DEBUG 2016-03-31 11:22:24,097 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('佛山鹏龙利泰', '983792'); args=[u'\u4f5b\u5c71\u9e4f\u9f99\u5229\u6cf0', u'983792']
DEBUG 2016-03-31 11:22:24,103 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('佛山怡和仁孚', '970237'); args=[u'\u4f5b\u5c71\u6021\u548c\u4ec1\u5b5a', u'970237']
DEBUG 2016-03-31 11:22:24,110 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('顺德怡孚', '919676'); args=[u'\u987a\u5fb7\u6021\u5b5a', u'919676']
DEBUG 2016-03-31 11:22:24,116 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('仁孚怡邦', '899644'); args=[u'\u4ec1\u5b5a\u6021\u90a6', u'899644']
DEBUG 2016-03-31 11:22:24,122 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('广州龙星行', '429033'); args=[u'\u5e7f\u5dde\u9f99\u661f\u884c', u'429033']
DEBUG 2016-03-31 11:22:24,130 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('广州仁孚', '486002'); args=[u'\u5e7f\u5dde\u4ec1\u5b5a', u'486002']
DEBUG 2016-03-31 11:22:24,137 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('广州鸿粤星辉', '574719'); args=[u'\u5e7f\u5dde\u9e3f\u7ca4\u661f\u8f89', u'574719']
DEBUG 2016-03-31 11:22:24,143 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('广州锦星行', '545860'); args=[u'\u5e7f\u5dde\u9526\u661f\u884c', u'545860']
DEBUG 2016-03-31 11:22:24,148 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('广州中升之星', '997519'); args=[u'\u5e7f\u5dde\u4e2d\u5347\u4e4b\u661f', u'997519']
DEBUG 2016-03-31 11:22:24,154 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('广州龙星骏宜', '700061'); args=[u'\u5e7f\u5dde\u9f99\u661f\u9a8f\u5b9c', u'700061']
DEBUG 2016-03-31 11:22:24,161 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('福州东星', '315275'); args=[u'\u798f\u5dde\u4e1c\u661f', u'315275']
DEBUG 2016-03-31 11:22:24,166 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('福州利之星', '740635'); args=[u'\u798f\u5dde\u5229\u4e4b\u661f', u'740635']
DEBUG 2016-03-31 11:22:24,174 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('福建波士骏达', '840140'); args=[u'\u798f\u5efa\u6ce2\u58eb\u9a8f\u8fbe', u'840140']
DEBUG 2016-03-31 11:22:24,180 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('福建波士运达', '987463'); args=[u'\u798f\u5efa\u6ce2\u58eb\u8fd0\u8fbe', u'987463']
DEBUG 2016-03-31 11:22:24,187 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('福州鹏龙国戎', '952322'); args=[u'\u798f\u5dde\u9e4f\u9f99\u56fd\u620e', u'952322']
DEBUG 2016-03-31 11:22:24,197 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('湖南龙星行', '714801'); args=[u'\u6e56\u5357\u9f99\u661f\u884c', u'714801']
DEBUG 2016-03-31 11:22:24,203 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('湖南仁孚', '902643'); args=[u'\u6e56\u5357\u4ec1\u5b5a', u'902643']
DEBUG 2016-03-31 11:22:24,209 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('湖南鹏龙瑞丰', '902710'); args=[u'\u6e56\u5357\u9e4f\u9f99\u745e\u4e30', u'902710']
DEBUG 2016-03-31 11:22:24,215 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('湖南华美', '986811'); args=[u'\u6e56\u5357\u534e\u7f8e', u'986811']
DEBUG 2016-03-31 11:22:24,222 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('东莞溢华（南城店）', '261942'); args=[u'\u4e1c\u839e\u6ea2\u534e\uff08\u5357\u57ce\u5e97\uff09', u'261942']
DEBUG 2016-03-31 11:22:24,228 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('东莞溢华（长安店）', '289697'); args=[u'\u4e1c\u839e\u6ea2\u534e\uff08\u957f\u5b89\u5e97\uff09', u'289697']
DEBUG 2016-03-31 11:22:24,233 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('寮步仁孚', '460752'); args=[u'\u5bee\u6b65\u4ec1\u5b5a', u'460752']
DEBUG 2016-03-31 11:22:24,238 utils (0.000) INSERT INTO `portal_backuser` (`service_name`, `password`) VALUES ('中升奔驰厚街店', '700586'); args=[u'\u4e2d\u5347\u5954\u9a70\u539a\u8857\u5e97', u'700586']
DEBUG 2016-03-31 12:01:06,015 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:01:06,068 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:01:06,069 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 12:01:06,074 utils (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
WARNING 2016-03-31 12:01:08,761 base Not Found: /portal/login
DEBUG 2016-03-31 12:01:08,767 base Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
ERROR 2016-03-31 12:01:08,769 base Internal Server Error: /portal/login
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 114, in process_response
    if self.should_redirect_with_slash(request):
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 79, in should_redirect_with_slash
    and urlresolvers.is_valid_path('%s/' % request.path_info, urlconf)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 668, in is_valid_path
    resolve(path, urlconf)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 534, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 376, in resolve
    sub_match = pattern.resolve(new_path)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 248, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 255, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/benz/venv/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
    result = user_function(*args, **kwds)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/urlresolvers.py", line 115, in get_callable
    mod = import_module(mod_name)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/benz/portal/views.py", line 99
    "data":{
          ^
SyntaxError: invalid syntax
DEBUG 2016-03-31 12:01:36,287 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:01:36,336 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:01:36,337 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 12:01:36,340 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
WARNING 2016-03-31 12:01:38,809 base Not Found: /portal/login
DEBUG 2016-03-31 12:01:38,813 base Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
ERROR 2016-03-31 12:01:38,892 base Internal Server Error: /portal/login
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 115, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 99, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/portal/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
DEBUG 2016-03-31 12:02:55,603 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:02:55,647 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:02:55,648 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 12:02:55,651 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 12:03:24,059 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:03:24,111 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:03:24,112 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 12:03:24,116 utils (0.001) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
WARNING 2016-03-31 12:03:25,757 base Not Found: /portal/login
DEBUG 2016-03-31 12:03:25,761 base Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
ERROR 2016-03-31 12:03:25,841 base Internal Server Error: /portal/login
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 235, in get_response
    response = middleware_method(request, response)
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 115, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "/home/benz/venv/lib/python2.7/site-packages/django/middleware/common.py", line 99, in get_full_path_with_slash
    'url': request.get_host() + new_path,
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/portal/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
DEBUG 2016-03-31 12:03:47,141 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:03:47,142 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:03:47,143 utils (0.001) SELECT `portal_backuser`.`id`, `portal_backuser`.`service_name`, `portal_backuser`.`password` FROM `portal_backuser` WHERE `portal_backuser`.`service_name` = '南宁恒信之星'; args=(u'\u5357\u5b81\u6052\u4fe1\u4e4b\u661f',)
DEBUG 2016-03-31 12:04:11,194 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:04:11,254 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:04:11,255 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 12:04:11,259 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
WARNING 2016-03-31 12:04:25,435 base Not Found: /portal/download
DEBUG 2016-03-31 12:04:25,440 base Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/template/base.py", line 905, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [name] in u'<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
DEBUG 2016-03-31 12:04:25,552 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:04:25,554 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:04:25,555 utils (0.001) SELECT `portal_user`.`id`, `portal_user`.`name`, `portal_user`.`mobile`, `portal_user`.`email`, `portal_user`.`sex`, `portal_user`.`province`, `portal_user`.`city`, `portal_user`.`service_name` FROM `portal_user` WHERE `portal_user`.`service_name` = '南宁恒信之星'; args=(u'\u5357\u5b81\u6052\u4fe1\u4e4b\u661f',)
ERROR 2016-03-31 12:04:25,559 base Internal Server Error: /portal/download/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 118, in download
    f.save("static/data/"+request.session['BKUSER']+".xls")
  File "/home/benz/venv/lib/python2.7/site-packages/xlwt/Workbook.py", line 696, in save
    doc.save(filename_or_stream, self.get_biff_data())
  File "/home/benz/venv/lib/python2.7/site-packages/xlwt/CompoundDoc.py", line 262, in save
    f = open(file_name_or_filelike_obj, 'w+b')
IOError: [Errno 2] No such file or directory: u'static/data/\u5357\u5b81\u6052\u4fe1\u4e4b\u661f.xls'
DEBUG 2016-03-31 12:04:51,410 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:04:51,458 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:04:51,459 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 12:04:51,462 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 12:04:52,770 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:04:52,772 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:04:52,773 utils (0.001) SELECT `portal_user`.`id`, `portal_user`.`name`, `portal_user`.`mobile`, `portal_user`.`email`, `portal_user`.`sex`, `portal_user`.`province`, `portal_user`.`city`, `portal_user`.`service_name` FROM `portal_user` WHERE `portal_user`.`service_name` = '南宁恒信之星'; args=(u'\u5357\u5b81\u6052\u4fe1\u4e4b\u661f',)
DEBUG 2016-03-31 12:06:32,058 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:06:32,110 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:06:32,112 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-03-31 12:06:32,115 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
DEBUG 2016-03-31 12:06:38,674 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:06:38,675 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-03-31 12:06:38,676 utils (0.000) SELECT `portal_user`.`id`, `portal_user`.`name`, `portal_user`.`mobile`, `portal_user`.`email`, `portal_user`.`sex`, `portal_user`.`province`, `portal_user`.`city`, `portal_user`.`service_name` FROM `portal_user` WHERE `portal_user`.`service_name` = '南宁恒信之星'; args=(u'\u5357\u5b81\u6052\u4fe1\u4e4b\u661f',)
DEBUG 2016-04-01 04:57:30,937 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-04-01 04:57:30,991 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-04-01 04:57:30,993 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-04-01 04:57:30,996 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
ERROR 2016-04-01 04:57:49,046 base Internal Server Error: /portal/update_access_token/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 47, in update_access_token
    get_js_ticket(get_access_token(appid, secret), appid, secret)
  File "/home/benz/portal/plugin.py", line 33, in get_access_token
    cache.set("access_token", res['access_token'], settings.NEVER_REDIS_TIMEOUT)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/cache/__init__.py", line 98, in __getattr__
    return getattr(caches[DEFAULT_CACHE_ALIAS], name)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/cache/__init__.py", line 80, in __getitem__
    cache = _create_cache(alias)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/cache/__init__.py", line 54, in _create_cache
    "Could not find backend '%s': %s" % (backend, e))
InvalidCacheBackendError: Could not find backend 'redis_cache.RedisCache': No module named redis_cache
DEBUG 2016-04-01 04:58:52,339 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-04-01 04:58:52,403 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-04-01 04:58:52,404 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-04-01 04:58:52,408 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
ERROR 2016-04-01 04:58:53,523 base Internal Server Error: /portal/update_access_token/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 47, in update_access_token
    get_js_ticket(get_access_token(appid, secret), appid, secret)
  File "/home/benz/portal/plugin.py", line 33, in get_access_token
    cache.set("access_token", res['access_token'], settings.NEVER_REDIS_TIMEOUT)
  File "/home/benz/venv/lib/python2.7/site-packages/redis_cache/backends/base.py", line 32, in wrapped
    return method(self, client, key, *args, **kwargs)
  File "/home/benz/venv/lib/python2.7/site-packages/redis_cache/backends/base.py", line 282, in set
    result = self._set(client, key, self.prep_value(value), timeout, _add_only=False)
  File "/home/benz/venv/lib/python2.7/site-packages/redis_cache/backends/base.py", line 272, in _set
    return client.setex(key, value, timeout)
  File "/home/benz/venv/lib/python2.7/site-packages/redis/client.py", line 2014, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/benz/venv/lib/python2.7/site-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/home/benz/venv/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/benz/venv/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/benz/venv/lib/python2.7/site-packages/redis/connection.py", line 446, in connect
    self.on_connect()
  File "/home/benz/venv/lib/python2.7/site-packages/redis/connection.py", line 514, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/home/benz/venv/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: invalid password
DEBUG 2016-04-01 05:00:09,542 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-04-01 05:00:09,592 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-04-01 05:00:09,594 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-04-01 05:00:09,597 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
ERROR 2016-04-01 05:00:10,749 base Internal Server Error: /portal/update_access_token/
Traceback (most recent call last):
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/benz/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/benz/portal/views.py", line 47, in update_access_token
    get_js_ticket(get_access_token(appid, secret), appid, secret)
  File "/home/benz/portal/plugin.py", line 33, in get_access_token
    cache.set("access_token", res['access_token'], settings.NEVER_REDIS_TIMEOUT)
  File "/home/benz/venv/lib/python2.7/site-packages/redis_cache/backends/base.py", line 32, in wrapped
    return method(self, client, key, *args, **kwargs)
  File "/home/benz/venv/lib/python2.7/site-packages/redis_cache/backends/base.py", line 282, in set
    result = self._set(client, key, self.prep_value(value), timeout, _add_only=False)
  File "/home/benz/venv/lib/python2.7/site-packages/redis_cache/backends/base.py", line 272, in _set
    return client.setex(key, value, timeout)
  File "/home/benz/venv/lib/python2.7/site-packages/redis/client.py", line 2014, in setex
    return self.execute_command('SETEX', name, time, value)
  File "/home/benz/venv/lib/python2.7/site-packages/redis/client.py", line 572, in execute_command
    connection.send_command(*args)
  File "/home/benz/venv/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/benz/venv/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/benz/venv/lib/python2.7/site-packages/redis/connection.py", line 446, in connect
    self.on_connect()
  File "/home/benz/venv/lib/python2.7/site-packages/redis/connection.py", line 514, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/home/benz/venv/lib/python2.7/site-packages/redis/connection.py", line 582, in read_response
    raise response
ResponseError: invalid password
DEBUG 2016-04-01 05:00:39,042 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-04-01 05:00:39,092 utils (0.000) SET SQL_AUTO_IS_NULL = 0; args=None
DEBUG 2016-04-01 05:00:39,093 utils (0.001) SHOW FULL TABLES; args=None
DEBUG 2016-04-01 05:00:39,096 utils (0.000) SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`; args=()
